---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    MY_KEY: AgAyEJVi5Hn3lokPSoTk/zwhs/ywKwe7aPG1GqEJ+2x8yOXQiKWFAaTcPhEARSLFwkx31aF5+Dw0adm5/TCPaInZsSeKW0DPdAjFA7Zc8qZ44Ex9zA1m16LisREnwmNMr+uBu
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque

