---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCPDDmIblk/ofmBzybH6rbaQs+TGgax7VNrH+BYcqvgwyQT6kuRh3jAHEp4eEWPQHU1RJFzoZzyPUNFI7UgRH7jhWYpOR+mm1eUMDn852S2GJQRItYvf0kLkCxnmH7tF+4MhKBNsakcXwnwaOFIjEFkyD6cRAdMPJh8c7fAWfyh7x6gm4gElT6HRKiC8rlq7ti2cCzXQMCaGdIaNinbLgNsid/PrG6dM3eXGAs97cgIY5JHGjkvI2cQRpKHE/F+2NC6N7GE35fJ1Ds4CvZJJSbAUCANhKKol99zyBZPhnIyyuyGt6etwj9HFitW/TXQrtt+JV9NoWMcwDXBo2qYofuUHsUzG1p/GJYWZZaY7crofp1JEebfNiP7YqCSlISER+FT2IyC+Vsx689lRLCA75x57+VbCy354sWzjJ6DmbvU8d3BvEzPhx75/PUeVOj/ZOpspqqrtTO6ctlduE3lI8GbvD7wxRcz8WwS78tKvbBCfnW/2YcuLc4Vdugab4AjGp6VGcS84Pl1jIkuC68v/LVvq4Zq/vNBswNaPwWY2qdSIDubN5ENrKyGPrB51r2OrWYodqSOU3yRaOeIE3nIJaeJtqlc/u9RT3keXF0iKG40onmu6b/KxPYg+n7HaUtRgEty10oVLWIMjSVCKmyHYxwmHUxwOMMh3PHm1F6e36Zt52wqtFUDIl3QeAAjudqfEVf8VO0fSPYUnw==
    username: AgDIcMVH6OANvqknqlJDNNMXtKocFrFpH8CUtjCdgF87cnLE85Mm3eAa+osThPoXM/1mfwBcoxS23kr4KGzPi2gEpj7PqVemIJcISE9SA9qzFTSVudgYM9yxnwzkxcMJXQ80z3bAEAChfAMYd9dVxGQSynOHx8ihmYHjlAVtmL/DSmUfI9BaizZ4lhrfwXP/tI1/Z8tpFbLLx7CUk1kCzOLSOaBsI0RDcoOg9VPCHcq3a8LRP+ZPPmGQ93OLdxd4sQKJUyDx809wH58CAotMI7KZ7Mb8IMkV1ZI8tFSkIo6S4rkRI37UcvkqPhyn4YnBV7NeNwsqj0wpGqzgtc+pMj6mHNqXOy5xD4P6DA5dyuSrJSzGB3/rEDM2wKbtsqC9qyRq1tpeyfETv4sIQT1mpYWqHHvjiWH7H3d3LO4L6itA7Go/S0A1kd9CpzQewJ2n6eZWQ7lOtUn54erbaXy9Q/2oQsD0FJ5DZCsoibynXmAZg+PPelPf+EkJSBn082SJ4TRNqMncseUN1CiBul/7ahkEjv2ZlJZsmQqMQyUo48AWSCb1FSvrLx+rxbwKIFvrs9oZXZiWYJqMcJj/wBafdyD8kxg9EKHcy7TWC7BtRQCEVnYtt4ALhgT6Wmd5DszVPZVh9RsP6sKJNR1KfiqmV2BQaIRyxIszNL3MbhvLvWEmIoZdOAldrN6oC14e9qIMV96VlMoapw==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
