---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    MY_KEY: AgAyEJVi5Hn3lokPSoTk/zwhs/ywKwe7aPG1GqEJ+2x8yOXQiKWFAaTcPhEARSLFwkx31aF5+Dw0adm5/TCPaInZsSeKW0DPdAjFA7Zc8qZ44Ex9zA1m16LisREnwmNMr+uBuFoEW+/ORJz6kRosIsdUWzvRanBq0R96J+OWn2VwrOeAnaiZtr1k8X4vPhRSjfbe42fqEnEvhWdnvjCReCd/3gpBO69ulk+i1W6JN4xAz4OYXzj5pMv9moHGGQr3ugFDLTxaTvcOt25FQM9dyTtuRdtUptC43cKzrDKARzr3m7ZEl8Wxf3TUEBgS2LAUMFl9Ut4kCbOSbaH6sWJVPovEaC8YcluyJ71UK4oQOfncUFRZLYOFubFKxoXc8ZPpTzVZLRcu2BS06SnCYywRehZ5/on4o+HVQk69GH7BTjKiYTVk7ONABq1/JiTBBQ3AH43Q7e54HO9mzh9qoBpDhs83JkviKCHVxZWVsAelhiXXnmbsTWSPcZ7p7ZdvnSjK9ixlt+KHp4zdtKbXvahWq06yCodWbL2CLeGeOcIh18uuTiBmeDJysc6l9VYwv4gfM7+zQcraj8HB21Y3a1OuTIEsaFmYtO/KylxtwwlSPCWiuaMhiuxboPM9hjYw6SE+1HH2L0yahvTOk3PU7PwAQK4ygM3LtXA1+TsCMfYRIZ7dPe+fGFZU8/GhmxHqbmvcJCuhiJKqjf9ujGfgQA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
