---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    MY_KEY: AgAL1+GajjkixPz7cmdOt7nSbfRcOoqDU6PH2sxoiq17TJjrtPlsVDAwLgmykt13wS4yb8vzc0kA+2QpSVkthex4GfZCTHa21vVn73dR2Xk/aKpG6uyU8ij4o5qmj2vpZvOvJjLWogPyGCctzdgtu516Pf6rgu3xPoBwUN/MeCnncx8vFs/EFURkXsObfF0RRmmCU4vfmp3MIc8Doi2IgmP6k4k6b01WWQtBZsiSHGbkIDzX9SxU58FFSggpmyIOeCW8cF0amYoThFIjVafrfWtB/kRP4OUvKpJAyyI2oK7S0oYKrHoY2gt+jDvm8NyOJebBrlUkzObgC81ahQtEvmoD2SVPmpdTH7GnkWH+Ac8+6PJExexEshc4ieki4atv7yy4vomAHNG1Nv/qeVgvIiln8YtYIQsbZWkZAiGTt0W628muLLcvr2n3O2kPvaVDIOCsqThNnHRsvq1YYzeJzCH1Md7Xjct6fSFhkMen0KEIcMUSx7fO9Js6yGrQbL78fYaxlNkTGtekV0IsQufH5b/UpySlQCn8pQJMKN5mUYS/3kWBEtTkEYQYJoMXoDYmzMsib7BmwRLHrhOOIpvWuCYJ3i3AGrBcuPjrtugU+Mj1NrXYOrsSgsA5N0Gv4KleOiwVxzqkwV2dDaZN9/rAw/o5pnNnGj32nLI/XdGGafKfhdy0VLyfEXTZF9KgcSeCCAghwdGDjSr92sI0tA==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
