---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    MY_KEY: AgCrYLjmX1NtiqBAwKxfRgAI6CpIAVV9gZo70MGq1eCa3DiglRWvQG3KiGyHR7UvQoFHqXcaXVV15+YBZeN2b71XerDEXTDXNrJdE36mNpMW9Xjuj8u2arHJhLzrH1HPrEEuvKKt9cwYLtdOj9CvLpti8Po4k+jeZzepJqIDKgwddcgISB4DSWGpj/IqL8Amby7CuQTVj4hUA6xy3fBhxpLGn93QwxAPSgI8HkqE0FIhNUC/iXpAjwf7Pz9A+WGkGiIjLNxToHfpNKlFeaj2SdSGPGYm6hTDNTpufKQyP0kpO2EiWDLDoL6dMvQm8Rn5OCLhsE5qc0ayIYqH4M2LbZGlVSYTHLwopFsQgOFs/Tn6UnMecswNlHhBzNGaS1hmOFLaxNOOoznEJKIYWNs/1tM9IQr+UXtJEeWORoZOjT9jySrRBdFxxOYPC3dGbg5yPREFvIelV4uD8HpVmSxBxHNKfYC1bXZ/1sBKT+JqNjz6CCMogdZGgveBbe2gsrID6WgDNiurcBiWBOaz4bM4+bwqq4XKQmEqHwyr6GP3PTBhcZRZrUUoq0RFfbEzT/nYE4+7+Md+Gb0aUr7692X1UDa5iEjB944MwpgCmIsTViYCKlZy7ha6XUxNIOugN5+WULRUHBgBUpEak9ruUuE4lL7mIwnRhsJIJSR6byT2vzU9q/VhvtwTaWVGpToc0DKQwmScKrjiMSGCj8in9A==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
