name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scans:
    name: Terraform and Dockerfile Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Install trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.64.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.64.1_Linux-64bit.deb

      - name: Run tfsec on Terraform code
        run: tfsec ./terraform

      - name: Run Trivy config scan on Terraform code
        run: trivy config ./terraform

      - name: Run Trivy filesystem scan
        run: trivy fs . --exit-code 0

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: security-scans

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-app:latest .

