name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t my-app:latest .

    - name: Run tfsec (Terraform security scan)
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        working-directory: ./terraform

    - name: Run Trivy (Docker image vulnerability scan)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-app:latest
        format: table
        exit-code: 0
        vuln-type: os,library
        severity: CRITICAL,HIGH

    - name: Apply SealedSecret to cluster (dry-run simulation)
      run: kubectl apply --validate=false -f k8s/sealed-secret.yaml

