name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    name: Terraform and Dockerfile Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec (Terraform scan)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          directory: terraform

      - name: Run Trivy (Dockerfile and secrets scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .

  docker-build:
    name: Build Docker Image
    needs: security-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-app:latest .

      # OPTIONAL: Push to Docker Hub
      # Uncomment and set secrets: DOCKER_USERNAME, DOCKER_PASSWORD
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker image
      #   run: docker push my-app:latest


